package constants

var (
	Nethttp                                                      = "net/http"
	Constants_0                                                  = ""
	Constants_2                                                  = ""
	Contextcanceled                                              = "context canceled"
	Providerpulltableerrors                                      = "provider pull table error: %s"
	HEROKUEMAIL                                                  = "HEROKU_EMAIL"
	Emailmustbeconfigured                                        = "email must be configured"
	Newclientserrs                                               = "new clients err: %s"
	Constants_5                                                  = "."
	Os                                                           = "os"
	Constants_1                                                  = ""
	Sselefraproviderheroku                                       = "%s selefra-provider-heroku"
	Constants_6                                                  = "*"
	NA                                                           = "N/A"
	Testing                                                      = "testing"
	Heroku                                                       = "heroku"
	Notsupported                                                 = "not_supported"
	SELEFRADATABASEDSN                                           = "SELEFRA_DATABASE_DSN"
	Hostuserpostgrespasswordpassportdbnamepostgressslmodedisable = "host=127.0.0.1 user=postgres password=pass port=5432 dbname=postgres sslmode=disable"
	Context                                                      = "context"
	Accountinformationnotfound                                   = "account information not found"
	Fmt                                                          = "fmt"
	HEROKUAPIKEY                                                 = "HEROKU_API_KEY"
	Analysisconfigerrs                                           = "analysis config err: %s"
	Errors                                                       = "errors"
	Strings                                                      = "strings"
	Constants_3                                                  = ""
	Apikeymustbeconfigured                                       = "api_key must be configured"
	V                                                            = "v0.0.1"
	Constants_4                                                  = ""
	Initprovidererrors                                           = "init provider error: %s"
)
